### ISSUE TITLE
"NameError: global name 'self' is not defined" in static FUSE._wrapper()

### ISSUE THREAD

**Issue by konstan** [fusepy/fusepy#124]
It's here https://github.com/fusepy/fusepy/blob/master/fuse.py#L756

This is the stacktrace.

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/Users/konstan/.virtualenvs/ssfs/lib/python2.7/site-packages/fuse.py", line 756, in _wrapper
    self.__critical_exception = e
NameError: global name 'self' is not defined
fuse: bad error value: 1346943168
```

**Comment by rianhunter** [comment]
this is fixed in #125

**Comment by mxmlnkn** [comment]
Unfortunately, I still noticed the same issue.
